CODABLE(UrfPgHdr)
  FIELD(uint8_t, BitsPerPixel)
  FIELD(uint8_t, ColorSpace)
  FIELD(uint8_t, Duplex)
  FIELD(uint8_t, Quality)
  PADDING(1)
  FIELD(uint8_t, MediaPos)
  PADDING(2)
  PADDING(4)
  FIELD(uint32_t, Width)
  FIELD(uint32_t, Height)
  FIELD(uint32_t, HWRes)
  PADDING(4)
  PADDING(4)
