name: C/C++ CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule sync --recursive && git submodule update --init --force --recursive --depth=1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpoppler-dev libpoppler-glib-dev libcurl4-openssl-dev
    - name: make
      run: make -j
    - name: make tests
      run: make -j
      working-directory: ./tests
    - name: test
      run: ./test
      working-directory: ./tests
    - name: analyze
      run: make analyze
