name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule sync --recursive && git submodule update --init --force --recursive --depth=1
    - name: make
      run: make -j
    - name: make tests
      run: make -j
      working-directory: ./tests
    - name: test
      run: ./test
      working-directory: ./tests

  build_clang:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule sync --recursive && git submodule update --init --force --recursive --depth=1
    - name: make
      run: CXX=clang++ make -j
    - name: make tests
      run: CXX=clang++ make -j
      working-directory: ./tests
    - name: test
      run: ./test
      working-directory: ./tests
