name: "Unit tests"


on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpoppler-dev libpoppler-glib-dev libcairo2-dev libglib2.0-dev libjpeg-dev libcurl4-openssl-dev zlib1g-dev
    - name: make
      run: make -j$(nproc)
    - name: make tests
      run: make -j$(nproc)
      working-directory: ./tests
    - name: test
      run: ./test
      working-directory: ./tests
